version: '3.8'

services:

  app:
    build: .
    container_name: dotnet_app
    ports:
      - "5042:8080"    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__develop=Server=database;Port=5432;Database=E_Commerce;User Id=postgres;Password=1234;
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      - postgres
      - redis
  
  postgres:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: E_Commerce
    ports:
      - "5433:5432"   
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379" 
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
